### ISSUE TITLE
Homework Feedback Node.js Week 2

### ISSUE THREAD

**Issue by r0hitsharma** [OlkaA/HYF#3]
Works well, minor feedback below:

https://github.com/OlkaA/HYF/blob/962abf99024d3cba966e49b0005df7109741da20/hyf-homework/nodeJS/homeworkWeek2/warmup/index.js#L5

Really good to show some instruction to the user. Just one thing, now that you know how to load files and process them as strings in Node.js (like you do with .json data files), you could place this in a `.html` file, load it and send that.

https://github.com/OlkaA/HYF/blob/962abf99024d3cba966e49b0005df7109741da20/hyf-homework/nodeJS/homeworkWeek2/warmup/index.js#L15

It's better not to place a lot of operations in a single line, otherwise debugging could be hard.

https://github.com/OlkaA/HYF/blob/962abf99024d3cba966e49b0005df7109741da20/hyf-homework/nodeJS/homeworkWeek2/MealSharing/src/backend/routes/meals.js#L25

Convention is to keep uppercase/titlecase for constants and classes (i.e. immutable objects).

**Comment by OlkaA** [comment]
Thank you for the feedback. I will improve my project.
